export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_REQUIRED = 'AUTH_TOKEN_REQUIRED',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',

  ACCESS_DENIED = 'ACCESS_DENIED',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ACADEMIC_RECORD_NOT_FOUND = 'ACADEMIC_RECORD_NOT_FOUND',
  DID_NOT_FOUND = 'DID_NOT_FOUND',
  CREDENTIAL_NOT_FOUND = 'CREDENTIAL_NOT_FOUND',
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',
  APPLICATION_NOT_FOUND = 'APPLICATION_NOT_FOUND',
  VERIFICATION_REQUEST_NOT_FOUND = 'VERIFICATION_REQUEST_NOT_FOUND',

  CREDENTIAL_REVOKED = 'CREDENTIAL_REVOKED',
  CREDENTIAL_SUSPENDED = 'CREDENTIAL_SUSPENDED',
  CREDENTIAL_EXPIRED = 'CREDENTIAL_EXPIRED',

  INVALID_CREDENTIAL_SIGNATURE = 'INVALID_CREDENTIAL_SIGNATURE',
  ISSUER_NOT_TRUSTED = 'ISSUER_NOT_TRUSTED',

  VERIFICATION_REQUEST_EXPIRED = 'VERIFICATION_REQUEST_EXPIRED',
  VERIFICATION_REQUEST_USED = 'VERIFICATION_REQUEST_USED',

  INVALID_NONCE = 'INVALID_NONCE',
  CLAIM_NOT_REQUESTED = 'CLAIM_NOT_REQUESTED',
  CLAIM_MISMATCH = 'CLAIM_MISMATCH',
  HOLDER_MISMATCH = 'HOLDER_MISMATCH',

  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  CONFLICT = 'CONFLICT',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',

  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
